name: Deploy Next.js Frontend

on:
  push:
    branches:
      - main   # only trigger on main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t frontend_admin .

      - name: Save Docker image
        run: docker save frontend_admin | gzip > frontend_admin.tar.gz

      - name: Upload image to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "frontend_admin.tar.gz"
          target: "~/"

      - name: Deploy on server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker load < ~/frontend_admin.tar.gz
            docker stop frontend_admin || true
            docker rm frontend_admin || true
            docker run -d -p 3000:3000 --name frontend_admin frontend_admin
